// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjwcszr8_wkykW90r7iaqcAqECIM_bwgE',
    appId: '1:231415821203:web:f8626f1102c6df9078ae66',
    messagingSenderId: '231415821203',
    projectId: 'latihan1pplg1',
    authDomain: 'latihan1pplg1.firebaseapp.com',
    storageBucket: 'latihan1pplg1.firebasestorage.app',
    measurementId: 'G-EQZKLPHDK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9w3YR_4G4APDsYb-OEGMOnIZi_u2Z8U',
    appId: '1:231415821203:android:bf1c6f0b05d81be278ae66',
    messagingSenderId: '231415821203',
    projectId: 'latihan1pplg1',
    storageBucket: 'latihan1pplg1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzcY0AI8NTO4Wg6ikDWIuHMUrRBT3Ab4',
    appId: '1:231415821203:ios:3c08229c74ea378778ae66',
    messagingSenderId: '231415821203',
    projectId: 'latihan1pplg1',
    storageBucket: 'latihan1pplg1.firebasestorage.app',
    iosBundleId: 'com.example.latihan111pplg1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuzcY0AI8NTO4Wg6ikDWIuHMUrRBT3Ab4',
    appId: '1:231415821203:ios:3c08229c74ea378778ae66',
    messagingSenderId: '231415821203',
    projectId: 'latihan1pplg1',
    storageBucket: 'latihan1pplg1.firebasestorage.app',
    iosBundleId: 'com.example.latihan111pplg1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjwcszr8_wkykW90r7iaqcAqECIM_bwgE',
    appId: '1:231415821203:web:0dacad7f46a2c49a78ae66',
    messagingSenderId: '231415821203',
    projectId: 'latihan1pplg1',
    authDomain: 'latihan1pplg1.firebaseapp.com',
    storageBucket: 'latihan1pplg1.firebasestorage.app',
    measurementId: 'G-Z8C20XE6F0',
  );
}